### ISSUE TITLE
Specify tracker's target

### ISSUE THREAD

**Issue by gallypette** [ail-project/ail-framework#102]
Sometimes a tracker yields numerous false positive on gist.github or other code-sharing pasties but almost only relevant items from tor crawling. Maybe it could be useful to able, when creating a tracker, to restrain the tracking to some sources, or some methods of collection (crawling only for instance).

**Comment by certrik** [comment]
That would be really useful indeed ...
https://github.com/ail-project/ail-framework/issues/43

**Comment by Terrtia** [comment]
Tracker sources selector is available and working as expected.
