### ISSUE TITLE
Splash Manager: Update note at every login - Possibility to deactivate?

### ISSUE THREAD

**Issue by certrik** [ail-project/ail-framework#106]
Hi, the update note "Update Note: v3.5 - Splash Manager" regarding splash manager appears at every login. Is it possible to deactivate it? I am already using splash manager but it seems that it is not recognised automatically.

**Comment by certrik** [comment]
Is it just me having the popup?

**Comment by Terrtia** [comment]
Hi @certrik !
Thanks for the report fixed with aa7317d
