### ISSUE TITLE
Question: How to optimize Web and WebStats queue? Filling up fast with monthly onion re-check

### ISSUE THREAD

**Issue by certrik** [ail-project/ail-framework#107]
Every month when all onion URLs are re-checked the Web and WebStats queues fill up very fast.
Is there any best practice to be able to optimize the configuration (AIL, DNS, ...)? Or things to avoid?

**Comment by Terrtia** [comment]
Fixed in AIL v5.0
The Web and WebStats modules have been removed from AIL.
