### ISSUE TITLE
yara - give more information regarding rules and strings that match

### ISSUE THREAD

**Issue by gallypette** [ail-project/ail-framework#108]
yara CLI has a `-s` switch that gives more information regarding rules and strings that matched:
```
       -s  --print-strings
              Print strings found in the file.
```
In practice, using this flag the output is:
```
name_rule file_matched
0xlocation_in_file:$string_var_name:string_content
```
It would be very useful to get this output somewhere, or having it used to have a better idea of what matched in a file.

**Comment by Terrtia** [comment]
First version to extract to show extracted/tracked content added in AIL v5.0
YARA match are highlighted in the Item content
