### ISSUE TITLE
thirdparty update: no module named pytaxonomies

### ISSUE THREAD

**Issue by th3r3d** [ail-project/ail-framework#11]
After last pull we getting this error, when trying to run AIL.

Traceback (most recent call last):
  File "./Flask_server.py", line 24, in <module>
    from pytaxonomies import Taxonomies
ModuleNotFoundError: No module named 'pytaxonomies'

I cannot find the module, which flask is looking for. I tried to run -t thirdparty update, but without luck. Can anyone help. Thank You

**Comment by Terrtia** [comment]
Hi @th3r3d !

It seem like there is an issue with the install/update of the PyTaxonomies library.

Can you please give me the output of the update thirdparty update ? (``./LAUNCH -t``)

**Comment by th3r3d** [comment]
looks like pytaxonomies are somewhere else ;-)
[ail-framework-output.txt](https://github.com/ail-project/ail-framework/files/4675777/ail-framework-output.txt)

**Comment by th3r3d** [comment]
I just -l instance and AIL is back again.
Thank You

**Comment by Terrtia** [comment]
Thanks for the feedback !
