### ISSUE TITLE
Credentials.py  item_id not found

### ISSUE THREAD

**Issue by TonyJabbour** [ail-project/ail-framework#121]
each time a leak is uploaded this error happens:

![image](https://user-images.githubusercontent.com/43400754/129045706-cd885d8a-c5c7-4493-b357-758db876f4f2.png)

**Comment by TonyJabbour** [comment]
I tried to replace item_id with items.id() didnt work

**Comment by Terrtia** [comment]
Hi @TonyJabbour !

Thanks for the report !
Fixed with caaa5d363f362c9f360199f69a93f45b6cf3d004
