### ISSUE TITLE
Can't feed pastes to ail

### ISSUE THREAD

**Issue by MayBeot** [ail-project/ail-framework#124]
I'm trying to use the pystemon feeder and it all seem to be working fine but nothing happens in ail.
It's the first time i'm trying to use ail so it's probably something i'm doing wrong.(I added some print() in pystemon feeder)

![Screenshot_20210825_185707](https://user-images.githubusercontent.com/89539116/130834619-4c95f9cb-c6b2-434c-b588-e430cef731d4.png)

**Comment by TonyJabbour** [comment]
Follow this you will be able to feed ail : https://github.com/ail-project/ail-framework/blob/master/HOWTO.md#feeding-ail-with-pystemon

**Comment by MayBeot** [comment]
I already followed that guide and it lead to this problem

**Comment by TonyJabbour** [comment]
check AIL screen `sudo screen -r Script_AIL`  for mixer and indexer etc.. any error ?

**Comment by MayBeot** [comment]
The output says: 
There is no screen to be resumed matching Script_AIL.

**Comment by MayBeot** [comment]
It works without sudo. There are a lot of screens with nothing in them, i'll write the ones that have some text:

No IP ranges provided

~/ail-framework$ 

Can't connect to Splash manager

Term Stats Cleaned

Global; ; ; ;glob Processed 0 item(s) in 31.144153118133545 s
Global; ; ; ;glob Processed 0 item(s) in 31.106388568878174 s

Press < ENTER > to launch the manager...

sleeping

Misp keys not present
The HIVE keys not present
