### ISSUE TITLE
Crawler question

### ISSUE THREAD

**Issue by MayBeot** [ail-project/ail-framework#128]
Is there a way to automatically add to the crawler queue any .onion website that are found while crawling?

**Comment by Terrtia** [comment]
Hi @MayBeot !

All onion domains are automatically sent to the crawler if an .onion url is found by AIL on a item (paste sites, crawled web/tor, manual or custom feeders). This way we can discover new onion domains.
All onion domains are crawled once by month (with one url depth by domain).

**Comment by MayBeot** [comment]
Thanks @Terrtia, so it's already a default feature, cool. So if the AIL i'm running is not doing it where should i look to find the problem?
I get the warnings about the onion domains detected in home but they are not added to the queue.
