### ISSUE TITLE
[ISSUE] Errors in crawler tab

### ISSUE THREAD

**Issue by SelfDestructAccount** [ail-project/ail-framework#133]
Hello,
By clicking on crawler tab, splash manager is deciding to kick me off after a timeout.
Attaching the Flask manager screen, i saw following error.

Somone else does encouter this issue ?
Regards

![image](https://user-images.githubusercontent.com/92041812/144597197-7597da21-b3b7-4fe3-99e9-2c0b9b738970.png)

Regards

**Comment by Terrtia** [comment]
Hi @SelfDestructAccount !
Thanks for the report and the error log !

Fixed with ebcffd4.

**Comment by SelfDestructAccount** [comment]
Thanks.
Update ok
