### ISSUE TITLE
Bug: Cannot add user

### ISSUE THREAD

**Issue by certrik** [ail-project/ail-framework#137]
Hi,
I recently tried to add another user to AIL but the user is never created.
![AIL_user_create_error](https://user-images.githubusercontent.com/42176839/153886032-a47b4caa-7e89-4e14-8d8c-a372901156dd.png)

**Comment by adulau** [comment]
Can you provide the commit-id and version of your AIL instance? I tried to reproduce on another instance without success.

**Comment by certrik** [comment]
It may have been an issue with the SSL certificate.

**Comment by certrik** [comment]
after full update from 4.0 to 4.1 and certificate renewel everything works as expected
