### ISSUE TITLE
cant install ail-framework on ubuntu or debian =( 

### ISSUE THREAD

**Issue by jotaah123** [ail-project/ail-framework#144]
i have an ubuntu 18.04 server (clean instalation)  and i have error with the instalation: 
 i follow the official instalation but dont work: 

root@vmi806047:~/ail-framework/bin# ./LAUNCH.sh -l

        * Checking configuration
Config File: Nothing to update
Config File: Nothing to update
        * Configuration up-to-date
******************************************************************
*                        Updating AIL ...                        *
******************************************************************
Check if this repository is a fork:
    This repository is a fork

... Updating fork ...
Fork Auto-Update disabled in config file

Aborting ...
******************************************************************
*                    AIL Not Updated                             *
******************************************************************

        * A screen is already launched
        * A screen is already launched
        * A screen is already launched
        * A screen is already launched
Could not connect to Redis at 127.0.0.1:6382: Connection refused
        6382 ARDB not ready
        Script not started, waiting 5 more secondes

**Comment by TonyJabbour** [comment]
Are you activating the ail environment?
Try to ./LAUNCH.sh -k before ./LAUNCH.sh -l
Try to use sudo to run ./LAUNCH.sh -l  and to kill

**Comment by jotaah123** [comment]
root@vmi806047:~/ail-framework/bin# ./LAUNCH.sh -k
Gracefully closing redis servers
Gracefully closing ardb servers
Could not connect to Redis at 127.0.0.1:6382: Connection refused
Killing all
No Sockets found in /run/screen/S-root.
        *       24421   24451   24470   24496       killed.


(i use sudo)

**Comment by Terrtia** [comment]
This is an ARDB install issue. Fixed in AIL v5.0
The database has been migrated from ARDB to Kvrocks.
