### ISSUE TITLE
OVA

### ISSUE THREAD

**Issue by KhaledEid020** [ail-project/ail-framework#184]
In the context of my professional responsibilities within my organization, I have been assigned the task of incorporating an open-source solution for monitoring activities on the dark web. 

While attempting to install this tool, I have encountered several technical issues. 

May I kindly request access to the pre-configured OVA file, which can be used to deploy the project within a virtual machine environment immediately?

**Comment by adulau** [comment]
As you have the time to send twitter messages and open an issue, I would highly recommend that you do a full installation of AIL on a production Linux server as you are responsible in your organisation with this task.  AIL installation on OVA are not considered appropriate for production use. The installation in the README on a production system is composed of 6 lines to be executed on a Linux server.

**Comment by KhaledEid020** [comment]
I am just facing errors during the installation,  I will try to solve it.

Can you tell me what version of Linux you used?

**Comment by adulau** [comment]
As mentioned in the README, an Ubuntu 22.04 LTS just works.
