### ISSUE TITLE
can not access the webpage  

### ISSUE THREAD

**Issue by KhaledEid020** [ail-project/ail-framework#185]
I am unable to access the webpage. Can you please investigate the issue and advise on the next steps?

![image](https://github.com/ail-project/ail-framework/assets/46486159/acaa2f5a-0eab-4d9f-b133-9f71bc6ca202)

I did that to install
###############################################
# Clone the repo first
git clone https://github.com/ail-project/ail-framework.git
cd ail-framework

# For Debian and Ubuntu based distributions
./installing_deps.sh

# Launch ail
cd ~/ail-framework/
cd bin/
./LAUNCH.sh -l

**Comment by KhaledEid020** [comment]
![image](https://github.com/ail-project/ail-framework/assets/46486159/fc3a1874-5bfe-4f8e-94d5-32526e767315)

**Comment by KhaledEid020** [comment]
![image](https://github.com/ail-project/ail-framework/assets/46486159/6cf946ff-d303-47b4-9958-e7666320e051)

**Comment by Graymanre** [comment]
> ![image](https://user-images.githubusercontent.com/46486159/276341147-fc3a1874-5bfe-4f8e-94d5-32526e767315.png)

This image says it all right? The flask server cannot import "url_decode" from werkzeug.urls
The exact error is often due to the installation of a flask-login version that is incompatible with flask-login
Try this: 

`pip install werkzeug==2.3.0`

**Comment by KhaledEid020** [comment]
Thanks it worked but I face another error here:
https://github.com/ail-project/ail-framework/issues/186
