### ISSUE TITLE
Error 111 connecting to localhost:6382. 

### ISSUE THREAD

**Issue by KhaledEid020** [ail-project/ail-framework#186]
I will be appreciated for any help 

![276517158-3cc5d7ae-edb5-4b93-9392-bd6383efc347](https://github.com/ail-project/ail-framework/assets/46486159/9c3c81c1-92a6-4088-b4a4-48c6c36d5b51)

**Comment by KhaledEid020** [comment]
![image](https://github.com/ail-project/ail-framework/assets/46486159/9e85c11a-ac1c-4600-8d79-dc39b450e30b)

**Comment by adulau** [comment]
Your kvrocks is not running. Did you LAUNCH it before?

**Comment by KhaledEid020** [comment]
> Your kvrocks is not running. Did you LAUNCH it before?


What is "kvrocks" and how I LAUNCH it?
