### ISSUE TITLE
No Feeds data in my Dashboard

### ISSUE THREAD

**Issue by threathunter369** [ail-project/ail-framework#192]
Hi Team

Good Day,

Let me ask for your assistance, How can i Enable the Feeders on my Dashboard? It seems no feeds are working as of the moment, That's why there is no data on my dashboard?

Do we have to setup a proxy for the Feeds or Leaks Data to be safe or not necessarily?

![AIL Feed](https://github.com/ail-project/ail-framework/assets/118037314/242e7361-b00a-4d04-b864-8f2ef2e6e9c0)

Kindly assist. 

Thank You in Advance.

**Comment by sudeepbogati7** [comment]
facing the same problem 

what did you do ? 
I would appreciate your assistance

**Comment by adulau** [comment]
I bet this is outdated with recent version of AIL as the dashboard has been rewritten.
