### ISSUE TITLE
Flask problems due to update_thirdparty.sh not working

### ISSUE THREAD

**Issue by markus-lassfolk** [ail-project/ail-framework#194]
**Problem:** 
When calling update_thirdparty.sh it does not provide any errors and just quits without any warning, resulting in Flask not having any CSS, JS and Fonts, and also not the other dependencies handled by that file. 

**Cause:** 
These source files does not exist any longer for the start bootstrap, Github giving an 404 Error as the project has been removed. 

```
wget -q https://github.com/BlackrockDigital/startbootstrap-sb-admin/archive/v${SBADMIN_VERSION}.zip -O temp/${SBADMIN_VERSION}.zip
wget -q https://github.com/BlackrockDigital/startbootstrap-sb-admin-2/archive/v${SBADMIN_VERSION}.zip -O temp/${SBADMIN_VERSION}-2.zip
```

**Workaround:** 
before running the update script, with NPM install the bootstraps; 

```
sudo apt install npm 
npm install startbootstrap-sb-admin@3.3.7
npm install startbootstrap-sb-admin-2@3.3.7

```  

then modify update_thirdparty.sh 

line 3 to (comment the line) 
`# set -e   ` 

line 44 and line 45 to something like 
```
mv ~/node_modules/startbootstrap-sb-admin temp/sb-admin
mv ~/node_modules/startbootstrap-sb-admin-2 temp/sb-admin-2
```

So it copies the files from the npm modules directory to the temp folder to let it work with the rest of the script moving files to the static folder.

**Comment by markus-lassfolk** [comment]
Actually, just noticed the problem is a bit larger. 

When installing_deps.sh runs,  it calls on /install_virtualenv.sh

From: installing_deps.sh
```
# Config File
if [ ! -f configs/core.cfg ]; then
    cp configs/core.cfg.sample configs/core.cfg
fi

# create AILENV + install python packages
./install_virtualenv.sh

```

in  ./install_virtualenv.sh it's also calling on the update_thirdparty.sh
```
pushd ${AIL_FLASK}
./update_thirdparty.sh
popd

```

The result is that installing_deps.sh is also not completing and anything here is not executed and done; 

```
# force virtualenv activation
if [ -z "$VIRTUAL_ENV" ]; then
    . ./AILENV/bin/activate
fi

pushd ${AIL_HOME}/tools/gen_cert
./gen_root.sh
wait
./gen_cert.sh
wait
popd

cp ${AIL_HOME}/tools/gen_cert/server.crt ${AIL_FLASK}/server.crt
cp ${AIL_HOME}/tools/gen_cert/server.key ${AIL_FLASK}/server.key

mkdir -p $AIL_HOME/PASTES

#### DB SETUP ####

# init update version
pushd ${AIL_HOME}
# shallow clone
git fetch --depth=500 --tags --prune
if [ ! -z "$TRAVIS" ]; then
    echo "Travis detected"
    git fetch --unshallow
fi
git describe --abbrev=0 --tags | tr -d '\n' > ${AIL_HOME}/update/current_version
echo "AIL current version:"
git describe --abbrev=0 --tags
popd

# LAUNCH Kvrocks
bash ${AIL_BIN}/LAUNCH.sh -lkv &
wait
echo ""

# create default user
pushd ${AIL_FLASK}
python3 create_default_user.py
popd

bash ${AIL_BIN}/LAUNCH.sh -k &
wait
echo ""
```

All because update_thirdparty.sh contains "set -e" which terminates the script and all actions if any command in the script fails, which they currently do due to the broken Bootstrap links.

**Comment by Terrtia** [comment]
Thanks for the report !

I removed the sb-admin and sb-admin2 dependencies.
I'll improve the error output

**Comment by adulau** [comment]
Fixed as mentioned by @Terrtia
