### ISSUE TITLE
CRITICAL:root:twint.run:Twint:Feed:noData'globalObjects'

### ISSUE THREAD

**Issue by paulie007** [ail-project/ail-framework#197]
Getting this error when running python3 feeder.py "pastebin.com"

Ubuntu 22.04
python 3.10

CRITICAL:root:twint.run:Twint:Feed:noData'globalObjects'
sleeping for 1.0 secs
CRITICAL:root:twint.run:Twint:Feed:noData'globalObjects'
sleeping for 8.0 secs
Alarm clock

**Comment by adulau** [comment]
The API and search interface of Twitter has been closed when it moved to X. Twint is not supposed to work any more.
