### ISSUE TITLE
 Crawler Disabled -  Error: Lacus URL undefined 

### ISSUE THREAD

**Issue by tominovoj** [ail-project/ail-framework#200]
Hello,

I was followed installation steps but I was not successful in connection AIL with Lacus - both seems work, but in AIL I have still status code 400. Can somebody help me what could be reason?

It would be great have community discord channel for such issues. Thank for great project!

![issue](https://github.com/ail-project/ail-framework/assets/116872706/2c47a6b5-995e-4599-86e7-f261c0830d3a)

**Comment by Sylvesle89** [comment]
Hello,
Was there a resolution to this issue? We are running into the same thing with our Lacus install
