### ISSUE TITLE
problem with flask and port 7000 not up 

### ISSUE THREAD

**Issue by whitepoll** [ail-project/ail-framework#206]
good morning it is since yesterday that in spite of everything is ggiorn correctly and redone also the installation from 0 the flask server and port 7000 don't come back up 
This is the error screen image -r 57380.Flask_AIL
please could you help me to fix it?

![Screenshot 2024-02-06 alle 11 33 32](https://github.com/ail-project/ail-framework/assets/154346469/03b907e3-1825-4f77-a841-45b359995cb2)

**Comment by Terrtia** [comment]
Hi @whitepoll !
Thanks fr the report !
Fixed with 38a918e48580500c18896e6b7af30e49976e1ea2.

You need to reinstall flask:

```
cd ail-framework
. ./AILENV/bin/activate
pip install -U flask
```
