### ISSUE TITLE
Sync between two nodes - reason: "Invalid websocket url"

### ISSUE THREAD

**Issue by tominovoj** [ail-project/ail-framework#207]
Hello,

I am trying to connect two nodes, however getting following error `Invalid websocket url`. Can you help me what can be problem? I am sure that I have connect to `https://<ip>:7000` which I put as a AIL Server URL

Thanks!

**Comment by Terrtia** [comment]
Hello !

The websocket server is running by default on port 4443. you need to connect to ``wss://<ip>:4443``
Please note that I need to extend it to support Chats/Messages/Images/Screenshots

**Comment by adulau** [comment]
The thread is inactive. We close the ticket. If you think it's not solved, feel free to reopen it.
