### ISSUE TITLE
Pystemon not found error  ${AIL_HOME}

### ISSUE THREAD

**Issue by whitepoll** [ail-project/ail-framework#208]
Good morning,
I notice a problem in the configuration of pystemon.
During the installation of pystemon I cloned the git within the following pathway: 
/home/ail-framework/pystemon in this path we find the file pystemon.py.
Starting ail with ./LUNCH -f.
viewing screen we get the error in figure.. 
in the core.cfg file I entered the following path /home/ail-framework/pystemon/ 
what can be the error? 
Thanks 
Screen -r 229839.Feeder_Pystemon
<img width="1048" alt="image" src="https://github.com/ail-project/ail-framework/assets/154346469/e82b57ad-dc81-419e-b4ca-c3e5e8f64f9f">

core.cfg
<img width="724" alt="image" src="https://github.com/ail-project/ail-framework/assets/154346469/95138f0f-c5bd-4535-bffc-b2fda2df1e1e">

**Comment by Terrtia** [comment]
Hello!

Which version/repository of pystemon are you using ?

**Comment by whitepoll** [comment]
Hi I used the git-clone of the repository indicated on the Readme file (https://github.com/ail-project/ail-framework/blob/master/doc/README.md#ail-importers)
git cloned to the latest version: https://github.com/cvandeplas/pystemon

Structure of my directories:

![image](https://github.com/ail-project/ail-framework/assets/154346469/2f3dc16d-b944-4408-97a9-66dc6c28ef3a)
Thanks

**Comment by Terrtia** [comment]
Thanks for the report !
There was a typo in the documentation 57842c2ecf85acb99aaf2eca6873d5a649619dd3 c5f40d85a8e50af62d69b1648323f7c048e06088
Pystemon and AIL need to be installed in the same directory: ``/home/pystemon``

**Comment by whitepoll** [comment]
Now it works 
Thanks
