### ISSUE TITLE
Remote connect MISP and The hive 

### ISSUE THREAD

**Issue by vncloudsco** [ail-project/ail-framework#217]
I need instructions on connection MISP and The hive in the latest version I don't see a place to configure connections to these components. Please tell me how I can connect to the servers MISP and The hive ?  I found only enable or not option without connection configuration
![image](https://github.com/ail-project/ail-framework/assets/41409442/33cc3746-b532-46db-ae1b-4f2cbedcf6be)

**Comment by adulau** [comment]
The configs are available in the following directory: https://github.com/ail-project/ail-framework/tree/406d72bb5256c803b97f2be7d0710bd86774eaf7/configs/keys
