### ISSUE TITLE
Question about installing Lacus

### ISSUE THREAD

**Issue by Petzku12** [ail-project/ail-framework#221]
https://github.com/ail-project/lacus instruction says You need to have redis cloned and installed in the same directory you clone this template in: this repoitory and redis must be in the same directory, and not redis cloned in the this directory.
By installing the ail-framework, it also creates a redis folder in the /home/ail-framework directory. So do I use that already created redis folder or clone a new one? like there https://www.lookyloo.eu/docs/main/install-lookyloo.html#_install_redis. 
Do Lacus and Lookyloo need their own redis installed? Could someone with a working system put a screenshot of their directory so I can see what to do. It took me a while to even get the ail-framework online. (Now I'm looking for a program to make a restore point so that I don't have to redo the whole installation again. )

Thank You

**Comment by Terrtia** [comment]
Hi @Petzku12 !
You don't need to clone a new Redis or recompile it. You can copy the Redis directory from the ``ail-framework`` into the same directory as Lacus.

What issues did you encounter during the installation of ail?

**Comment by Petzku12** [comment]
Hi @Terrtia 

At first I tried to install it on an old laptop which collected dust in the closet, but it ran out of power for this job. Then I installed WSL2 + Wlinux on this new laptop (32G cpu+6G vram), failed with lxd image and didn't succeed in cloning repo either.. There was always something wrong. 
How I even managed to get to localhost:7000 was that I installed a virtual machine (Ubuntu 22.04) in hyper-V. But that's where the joy ended and I gave up when after installing Lacus I couldn't access localhost:7100.
I removed everything and raised my hands. But now that I'm instructed, I'll try again today or tomorrow. Last time recompile old redis. Now I know it was a mistake.

Thank You

**Comment by Petzku12** [comment]
I got the ZTE MC801A 5G mobile router knotted when I was blindly trying to guess the settings to get AIL to work. I have come to the conclusion that the settings of that box is the reason why I can't access the AIL framework. Inside the box there are settings for portforward and APN etc . Anyone who knows about the soul life of such a box can sign up

**Comment by adulau** [comment]
Thanks for the feedback. We will close the issue.
