### ISSUE TITLE
Support of TRON addresses

### ISSUE THREAD

**Issue by pventuzelo** [ail-project/ail-framework#222]
Following our discussion with @adulau, here is some information to support TRON addresses in AIL.

# Context: External Account Creation

TRON’s key pair generation algorithm is the same as that of Ethereum, which uses the elliptic curve digital signature algorithm ECDSA-secp256k1. The process of key pair generation is: First, generate a random private key, which consists of 64 hexadecimal characters. Then, a public key is generated from the private key according to the Elliptic Curve Digital Signature Algorithm. Finally, take the last 20 bytes of the Keccak-256 result of the public key and add `41` in front of the Hex format address.

## Account Address Format

In addition to the Hex format, the TRON network account address also has a Base58 format.

- Hex
    
    Compared with the TRON address in Hex format generated by the same private key and the Ethereum address, except for the first 41, everything else is the same.
    
    ```
    418840E6C55B9ADA326D211D818C34A994AECED808
    
    ```
    
    Note: The TRON address in Hex format removes the leading `41` to get the Ethereum address.
    
- Base58
    
    A Base58 address can be obtained from the base check calculation of a Hex address. All Base58 addresses begin with T. For example:
    
    ```
    TNPeeaaFB7K9cmo4uQpcU32zGK8G1NYqeL
    
    ```
    
    Example of Hex and Base58 format conversion using [tronweb](https://github.com/tronprotocol/tronweb):
    
``` JavaScript
    
    `tronWeb.address.toHex("TNPeeaaFB7K9cmo4uQpcU32zGK8G1NYqeL")
    > "418840E6C55B9ADA326D211D818C34A994AECED808"
    
    tronWeb.address.fromHex("418840E6C55B9ADA326D211D818C34A994AECED808")
    > "TNPeeaaFB7K9cmo4uQpcU32zGK8G1NYqeL"`
 ```

[Account (tron.network)](https://developers.tron.network/docs/account#external-account-creation)

# Detection: with simple regex

A simple regex to detect potential Tron addresses will be: 

```python
^T[0-9a-zA-Z]{33}$
```

# Verification: Address checker

```python
import base58
import hashlib

def is_valid_tron_address(tron_address):
    """Validates a Tron address."""
    if not isinstance(tron_address, str) or not tron_address.startswith('T') or len(tron_address) < 4:
        return False

    try:
        decoded_address = base58.b58decode(tron_address)
    except ValueError:
        # This catches errors in base58 decoding due to invalid characters or other issues
        return False

    if len(decoded_address) != 25:  # Expected length for Tron addresses after decoding
        return False

    # Split the address into the checksum and the payload
    checksum = decoded_address[-4:]
    payload = decoded_address[:-4]

    # Perform double SHA-256 hashing on the payload
    hash1 = hashlib.sha256(payload).digest()
    hash2 = hashlib.sha256(hash1).digest()

    # The first 4 bytes of the second hash should match the checksum
    return checksum == hash2[:4]
```

Unit-tests:

```python
# Test valid address
print(is_valid_tron_address('TYdds9VLDjUshf9tbsXSfGUZNzJSbbBeat'))

# Test invalid addresses
invalid_tron_addresses = [
    "T9ukMPj9NEUsW5CoRoWvQTeG4a9XQF8f2J",  # Altered checksum (Assuming a valid start)
    "T9ukMPj9NEUsW5CoRoWvQTeG",  # Too short
    "T9ukMPj9NEUsW5CoRoWvQTeG4a9XQF8f2Jabcdef",  # Too long
    "T9ukMP0jNEUsW5CoRoWvQTeG4a9XQF8f2J",  # Invalid character (0)
    "I9ukMPj9NEUsW5CoRoWvQTeG4a9XQF8f2J",  # Invalid character (I), and incorrect prefix
    "l9ukMPj9NEUsW5CoRoWvQTeG4a9XQF8f2J",  # Invalid character (l), and incorrect prefix
    "O9ukMPj9NEUsW5CoRoWvQTeG4a9XQF8f2J",  # Invalid character (O), and incorrect prefix
    "69ukMPj9NEUsW5CoRoWvQTeG4a9XQF8f2J",  # Incorrect prefix (not starting with 'T')
    "T9ukMPj9NEUsW5CoRoWvQTeG4a9XQF8f2!",  # Invalid character (!)
    "T9ukMPj9NEUsW5CoRoWvQTeG4a9XQF8f2_",  # Invalid character (_)
    "T9ukMPj9NEUsW5CRoWvQTeG4a9XQF8f2J",  # Replaced 'o' with 'R', altering checksum validity
    "T" + "1"*33,  # Invalid character (1), correct length but invalid character for base58
    "T" + "A"*33,  # Consistent character, unlikely to pass checksum
    "T9ukMPj9NEUsW5CoRoWvQT",  # Significantly short
    "T" + "9"*45,  # Significantly long
    "G9ukMPj9NEUsW5CoRoWvQTeG4a9XQF8f2J",  # Incorrect prefix (G instead of T)
    "T9ukMPj9N$UsW5CoRoWvQTeG4a9XQF8f2J",  # Special character ($)
    "T9ukMPj9NEUsW5CoRoWvQTeG4a9XQF8f2" + "J"*10,  # Repetitive character at the end, too long
    "M9ukMPj9NEUsW5CoRoWvQTeG4a9XQF8f2J",  # Incorrect prefix (M instead of T)
    "T9ukMPj9NEUsW5CoRoWvQTeG4a9XQF8f2?",  # Special character (?)
]

for addr in invalid_tron_addresses:
  print(is_valid_tron_address(addr))
```

# Contact

- Patrick from @fuzzinglabs

**Comment by adulau** [comment]
Thanks a lot for the insightful details! We will add it.

**Comment by Terrtia** [comment]
Thank you!
TRON Detection and correlation have been added to AIL:  0dfd92bcd608bdd1d6f0d4354947a73c630a28e8
