### ISSUE TITLE
webhook not saved in dict_tracker

### ISSUE THREAD

**Issue by dimovys** [ail-project/ail-framework#223]
Greetings! I'm trying to set up a webhook for trackers and I'm faced with the fact that the webhook is not saved when creating and changing traskers. I couldn't debug the project on my own :(
![image](https://github.com/ail-project/ail-framework/assets/99807281/2f71ef94-9529-4e3b-a160-20df5a6ae6c6)
![image](https://github.com/ail-project/ail-framework/assets/99807281/c9fa2281-f6f9-4616-96f0-eb29a7f5dfee)

**Comment by dimovys** [comment]
I found 1 more bug, if you disable these parameters, they will be disabled, but with a new edit they will be enabled, and if you do not disable them again, they will be enabled after editing.
![image](https://github.com/ail-project/ail-framework/assets/99807281/1da7e2ef-743a-4eb0-8abd-1a6a6aee39f5)
![image](https://github.com/ail-project/ail-framework/assets/99807281/e56b0425-4a3c-43b9-a2e4-c2f375a8efe9)
![image](https://github.com/ail-project/ail-framework/assets/99807281/a9b68de6-ed71-464c-8d50-d373a2ee844e)
![image](https://github.com/ail-project/ail-framework/assets/99807281/5234815f-5a33-4d93-9df6-7c7b281993d0)

**Comment by fearanp** [comment]
Hi,

Just to add to the webhook scenario......

When i try to save a webhook url to a REGEX, WORD or YARA tracker i get the same blank output as above .the output from the screen is below but it doesnt save any value

`"POST /tracker/edit HTTP/1.0" 302 -
"GET /tracker/show?uuid=d8b0337a-1ab5-4fcf-b70e-9338065a28c3 HTTP/1.0" 200 -
"GET /static/css/bootstrap4.min.css HTTP/1.0" 304 -
"GET /static/css/font-awesome.min.css HTTP/1.0" 304 -
"GET /static/css/daterangepicker.min.css HTTP/1.0" 304 -
"GET /static/css/dataTables.bootstrap.min.css HTTP/1.0" 304 -
"GET /static/js/jquery.js HTTP/1.0" 304 -
"GET /static/js/popper.min.js HTTP/1.0" 304 -
"GET /static/js/bootstrap4.min.js HTTP/1.0" 304 -
"GET /static/js/jquery.dataTables.min.js HTTP/1.0" 304 -
"GET /static/js/dataTables.bootstrap.min.js HTTP/1.0" 304 -
"GET /static/js/d3.min.js HTTP/1.0" 304 -
"GET /static/js/d3/sparklines.js HTTP/1.0" 304 -
"GET /static/js/d3/graphlinesgroup.js HTTP/1.0" 304 -
"GET /static/js/moment.min.js HTTP/1.0" 304 -
"GET /static/js/jquery.daterangepicker.min.js HTTP/1.0" 304 -
"GET /static/image/ail-project-inverted.png HTTP/1.0" 304 -
"GET /tracker/graph/json?uuid=d8b0337a-1ab5-4fcf-b70e-9338065a28c3 HTTP/1.0" 200 -`

If i try to add a webhook to a SET tracker i get a internal 500 server error and the below output on screen

`ERROR in app: Exception on /tracker/edit [POST]
Traceback (most recent call last):
  File "ail-framework/AILENV/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "ail-framework/AILENV/lib/python3.8/site-packages/flask/app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "ail-framework/AILENV/lib/python3.8/site-packages/flask/app.py", line 1506, in finalize_request
    response = self.make_response(rv)
  File "ail-framework/AILENV/lib/python3.8/site-packages/flask/app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'hunters.tracker_edit' did not return a valid response. The function either returned None or ended without a return statement.
Exception on /tracker/edit [POST]
Traceback (most recent call last):
  File "ail-framework/AILENV/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "ail-framework/AILENV/lib/python3.8/site-packages/flask/app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "ail-framework/AILENV/lib/python3.8/site-packages/flask/app.py", line 1506, in finalize_request
    response = self.make_response(rv)
  File "ail-framework/AILENV/lib/python3.8/site-packages/flask/app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'hunters.tracker_edit' did not return a valid response. The function either returned None or ended without a return statement.`

Hope this helps find the source of the issue as i am not having luck with setting up webhooks on trackers.

**Comment by Terrtia** [comment]
Hi @dimovys  @fearanp !
Thanks for the report !
Fixed with 1c0468e7c009cc493bb0229d6e6206c35ecc2efd

**Comment by dimovys** [comment]
webhook now saves but doesn't work :(
I have configured a webhook listener on a host with an ail-framework for debugging
![image](https://github.com/ail-project/ail-framework/assets/99807281/f642fcef-1aa3-4a5d-a78a-8d90d4a7cf54)
and am trying to send a webhook to it from a word type tracker
![image](https://github.com/ail-project/ail-framework/assets/99807281/10dbbcb6-d5f7-42c0-8963-5ed3258a7666)
![image](https://github.com/ail-project/ail-framework/assets/99807281/7877b9e1-aa73-48dc-8781-b9e35362a80f)
![image](https://github.com/ail-project/ail-framework/assets/99807281/346d1b1c-e3ac-4be6-879a-2ceff4d97f86)
and my local listener doesn't receive anything from ail-framework, but receives data from the curl request
curl -H 'Content-Type: application/json' -d '{ "title":"foo","body":"bar", "id": 1}' -X POST adress:8090
![image](https://github.com/ail-project/ail-framework/assets/99807281/2ca0fae1-03c2-4535-b827-c384dc190fbd)
