### ISSUE TITLE
BUG: Not able to add new cookie to existing cookiejar

### ISSUE THREAD

**Issue by arfe1012** [ail-project/ail-framework#226]
![grafik](https://github.com/ail-project/ail-framework/assets/81568991/de1ff767-ba86-4e79-a887-981426d9db54)
![grafik](https://github.com/ail-project/ail-framework/assets/81568991/3a797825-3dcb-47b4-a39c-a62cff2b4575)

**Comment by Terrtia** [comment]
Hi @arfe1012 !
Thanks for the report !
Fixed with 2dd42bf737ccc227945b8ad33e379f556fff31b0
