### ISSUE TITLE
webhook doesn't work :(

### ISSUE THREAD

**Issue by dimovys** [ail-project/ail-framework#228]
webhook doesn't work :(
I have configured a webhook listener on a host with an ail-framework for debugging
![image](https://github.com/ail-project/ail-framework/assets/99807281/f642fcef-1aa3-4a5d-a78a-8d90d4a7cf54)
and am trying to send a webhook to it from a word type tracker
![image](https://github.com/ail-project/ail-framework/assets/99807281/10dbbcb6-d5f7-42c0-8963-5ed3258a7666)
![image](https://github.com/ail-project/ail-framework/assets/99807281/7877b9e1-aa73-48dc-8781-b9e35362a80f)
![image](https://github.com/ail-project/ail-framework/assets/99807281/346d1b1c-e3ac-4be6-879a-2ceff4d97f86)
and my local listener doesn't receive anything from ail-framework, but receives data from the curl request
curl -H 'Content-Type: application/json' -d '{ "title":"foo","body":"bar", "id": 1}' -X POST adress:8090
![image](https://github.com/ail-project/ail-framework/assets/99807281/2ca0fae1-03c2-4535-b827-c384dc190fbd)

**Comment by fearanp** [comment]
just to add i havent gone that far but i can now save the webhook in each leak hunter module but it is not posting anything from ail framework, still looking for troubleshooting data to help further.

**Comment by Terrtia** [comment]
Hi @dimovys , @fearanp  !
Thanks for the report !
Fixed with 362d2ebdd2822eb1846544c8035832be9686328f
