### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by certrik** [ail-project/ail-framework#23]
I get `mv: Call of stat for 'temp/jquery.canvasjs.min.js' not possible: file or directory not found` .
It is the error message translated from German, so it may not be completely correct.

**Comment by certrik** [comment]
To give it a bit more context ... OS is Ubuntu 18.04 and I did a successful install from https://github.com/CIRCL/AIL-framework . After removing this installation because I realized that this repo here is the the correct one now I got the mentioned error.
Used `sudo` for installing both versions.
Could there be some deinstallation issue of the "old" version. If so it would be great to have some kind of uninstall instructions. 
Also it seems that `$AIL_HOME` is not set automatically via the installation process. 
It would be also great to have some reference that `dockerd` has to be started manually.
All in all a much more in depth and clear documentation would benefit the whole project I think. There is a lot of information to be found but not easily as the docu is a bit cluttered.

**Comment by certrik** [comment]
Found the error. It is in `update_thirdparty.sh` . Apparently `http://canvasjs.com/fdm/chart/` changed their structure to include also the beta versions (3.0) in the downloaded ZIP.
Changing 
`mv temp/jquery.canvasjs.min.js ./static/js/jquery.canvasjs.min.js`
to
`mv temp/canvasjs-2.3.2/Chart\ 2.3.2\ GA\ -\ Stable/jquery.canvasjs.min.js ./static/js/jquery.canvasjs.min.js`
resolves that for now.

**Comment by Terrtia** [comment]
HI @certrik !

Thank you !
Fixed with 7607cd742718b1c798ba2f650be2c5215ff2f863

``$AIL_HOME`` should be set by default in the installer. Did another error occurred during the installation ?

The old repository should work in the same way as the new one (It's just a mirror). The only difference is that the updater change the default remote if the old repository is used.
I'll investigate if there is an issue in the updater.

Regarding the crawler, a new crawler/spash manager will be released next week. This manager handle all the splash dockers, crawlers screen and proxy lists.

**Comment by certrik** [comment]
Hi @Terrtia ,
A crawler/splash manager seems like a great idea. I am looking forward to it.
Regarding $AIL_HOME ... it is not set when using `sudo ./bin/torcrawler/launch_splash_crawler.sh -f $AIL_HOME/configs/docker/splash_onion/etc/splash/proxy-profiles/ -p 8050 -n 1` from the HOWTO section at https://github.com/ail-project/ail-framework/blob/master/HOWTO.md .
One other good thing would be a statement which components and if things should be run as root or not. Also if `dockerd` would be better intergrated in the start process it would be great.

**Comment by certrik** [comment]
`canvasjs.com/fdm/chart/` points to `canvasjs-3.0.zip` rendering `update_thirdparty.sh` broken again.

**Comment by Terrtia** [comment]
HI @certrik !
Thanks for the report ! Fixed with 0d06f633e2c4e78f0c198d13ec49455abe616a0c.
I found a direct link to download canvasjs. (it shouldn't change anymore...)
