### ISSUE TITLE
Username and Password

### ISSUE THREAD

**Issue by antmar904** [ail-project/ail-framework#234]
Hi.

I installed AIL on Ubuntu in WSL for Windows.  I am at the logon screen here: https://localhost:7000/login but I never setup an account during the installation process so I'm not sure what the logon creds are.

**Comment by Terrtia** [comment]
Hi @antmar904 !

A ``DEFAULT_PASSWORD`` file is created by default in the ail-framework directory. 
This file is deleted on the first login.

**Comment by antmar904** [comment]
Yes I saw that in the docs but I can't find that file.  It does not exist.

**Comment by Terrtia** [comment]
If you already log in, you can reset the default admin password:
```bash
cd ail-framework
. ./AILENV/bin/activate
cd var/www
./create_default_user.py
```

**Comment by antmar904** [comment]
I have never logged in yet.

**Comment by Terrtia** [comment]
The password  can be reset with ``create_default_user.py``

**Comment by antmar904** [comment]
Thank you.  I am receiving an error when running:

`./create_default_user.py`

**Traceback (most recent call last):
  File "/home/user/ail-framework/var/www/./create_default_user.py", line 7, in <module>
    sys.path.append(os.environ['AIL_BIN'])
  File "/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'AIL_BIN'**

**Comment by Terrtia** [comment]
Please load the virtual ENV
```bash
cd ail-framework
. ./AILENV/bin/activate
cd var/www
./create_default_user.py
```

**Comment by antmar904** [comment]
Thank you very much!
I am in.
