### ISSUE TITLE
Detailed logs

### ISSUE THREAD

**Issue by certrik** [ail-project/ail-framework#24]
I am having problems getting email notifications up and running. So I am wondering if there is a place where detailed logs are stored or if there is some kind of debug mode or testscripts.

**Comment by Terrtia** [comment]
The logging system has been improved in AIL v5.0 to provide better troubleshooting.
logs are now located in the ``logs/`` directory.

You can ignore ``Crawler_warn*``, ``Script_warn*`` and ``Script_info*``. 
They will be removed soon (dashboard refactoring).

Logs files:
- ``logs/crawlers.logs``
-  ``logs/flask.logs``
-  ``logs/modules.logs``
-  ``logs/syncs.logs``
