### ISSUE TITLE
Increase blurring level for two specific tags

### ISSUE THREAD

**Issue by adulau** [ail-project/ail-framework#246]
Increase blurring level for two specific tags:

- `dark-web:topic="violence"`
- `dark-web:topic="pornography-illicit-or-illegal"`

Maybe we could make this configurable too?

**Comment by Terrtia** [comment]
List of tags updated: 4167b36d1a4a1616998a715cb7d26f4d73c41063

**Comment by adulau** [comment]
Thank you!
