### ISSUE TITLE
running pystemon.py has multiple indentation errors

### ISSUE THREAD

**Issue by perdigana** [ail-project/ail-framework#26]
(AILENV) ail@ail:~/AIL-framework$ cd pystemon/
(AILENV) ail@ail:~/AIL-framework/pystemon$ ./pystemon.py 
  File "./pystemon.py", line 69
    exit('You need python version 2.7 or newer.')
                                                ^
TabError: inconsistent use of tabs and spaces in indentation
(AILENV) ail@ail:~/AIL-framework/pystemon$ 

My goal is to feed data to AIL, but somehow I am unable to, been trying for a while now.

**Comment by Terrtia** [comment]
Hi @perdigana !

Do you have the same issue with this version of pystemon ?
https://github.com/cvandeplas/pystemon

**Comment by perdigana** [comment]
Hi @Terrtia ,

I just tested this version, it works for me now! Thanks!
