### ISSUE TITLE
Problems with YARA rules

### ISSUE THREAD

**Issue by certrik** [ail-project/ail-framework#31]
I love the YARA rules feature for leak hunter but it seems that there are some problems. When choosing a default rule like that
![grafik](https://user-images.githubusercontent.com/42176839/91218223-060dfc80-e719-11ea-9b00-da50ad2effa3.png)
an error is thrown ...
![grafik](https://user-images.githubusercontent.com/42176839/91218290-1b832680-e719-11ea-81a5-bf91fe1a7d7b.png)

**Comment by Terrtia** [comment]
Hi @certrik !

I encounter this issue one time. However I didn't manage to reproduce it. (I added some debug output)

Can you please update AIL?  If you still have this issue can you check the output of the flask server ?

**Comment by Terrtia** [comment]
Hi @certrik !

There was an issue with the virtualenv in the Launcher.
Fixed with 55ab603f27c4cf8d67579d9cd20c0dd759bd63a0.
