### ISSUE TITLE
Bug?: YARA tracker notification not working

### ISSUE THREAD

**Issue by certrik** [ail-project/ail-framework#41]
I am receiving notifications from my regex trackers without a problem but even if there was a hit in the YARA trackers, which can be seen in `/trackers` in the sparkline column, and configured email notification address, I don't receive anything.
I don't know how to debug that. Can you confirm for sure that email notification for YARA trackers is working properly?

**Comment by Terrtia** [comment]
Hi @certrik !
Thanks for the report ! Indeed there was an issue with the import of the mail template.
Fixed with b72cd978fcf35915367c43b9ffa07074ff48558b

I'll add an option to add the item content and tags in this template.
