### ISSUE TITLE
Flask not running

### ISSUE THREAD

**Issue by mouloren** [ail-project/ail-framework#46]
When I start AIL Flask it does not start and I force it with the -m option and it does not lift. Why would this happen?
Thank you and greetings

![image](https://user-images.githubusercontent.com/32422777/93195905-0ca4f800-f74a-11ea-85d7-b828cffad41a.png)
![image](https://user-images.githubusercontent.com/32422777/93195969-1af31400-f74a-11ea-988f-2d17c0a2d8fc.png)

**Comment by certrik** [comment]
If you could provide your /ail-framework/configs/core.cfg it should be of much help.
Also you could have a look for information or errors in screen -r Flask_AIL .
