### ISSUE TITLE
Bug: Cannot delete user

### ISSUE THREAD

**Issue by certrik** [ail-project/ail-framework#48]
I have added a read-only test user and wanted to delete it afterwards but it doesnt work.
<img width="1917" alt="delete_user_fails" src="https://user-images.githubusercontent.com/42176839/93340958-d2ad2200-f82d-11ea-9752-ea6fec9a74de.png">

**Comment by certrik** [comment]
I can delte another admin user though.
One special information which could be relevenat is that the read_only users email address is an alias (user+ailtest@domain.tld) of an already existing admin account (user@domain.tld) .

**Comment by certrik** [comment]
fixed with https://github.com/ail-project/ail-framework/commit/1a4c59502427f2ff308766989c242264d623d41c .
THX @Terrtia

**Comment by Terrtia** [comment]
Hi @certrik !
Thanks for the report and the example !
