### ISSUE TITLE
"SPLASH DOWN" when attempting to get web crawler working on normal domains.

### ISSUE THREAD

**Issue by tyler-esol** [ail-project/ail-framework#56]
The issue is shown in this screenshot 
![image](https://user-images.githubusercontent.com/70120515/95029159-f7d8d600-06f1-11eb-9182-d3542a049e28.png)
My logs do not show anything more than the timestamp and "splash down". My setup is on WSL1 based Ubuntu with my Ubuntu docker pointing at my docker desktop daemon.
I have followed to relevant setup for AIL, installed all of the relevant dependencies, setup TOR with “SOCKSPort 0.0.0.0:9050” and “SOCKSPolicy accept 172.17.0.0/16”, set up my core.cfg with splash_port=8050, activate_crawler = True and tried splash_url as http://127.0.0.1 and http://localhost.
Is there any additional things I have missed to get the webcrawler to work?

**Comment by Terrtia** [comment]
Fixed in AIL v5.0 release:
AIL crawler has been upgraded to [Lacus](https://github.com/ail-project/lacus)
A new test has been added in the UI to check if the crawler works as expected.
