### ISSUE TITLE
Leaks Hunter: Typo in URL

### ISSUE THREAD

**Issue by michael-hamm** [ail-project/ail-framework#58]
Emails send by tracker could have a typo. The '/' behind 'item' is to much.

Example: 
url: http://localhost:7000/object/item/?id=twitter/2020/10/26/1320854409954381830.gz

should be:
url: http://localhost:7000/object/item?id=twitter/2020/10/26/1320854409954381830.gz

**Comment by Terrtia** [comment]
Hi @michael-hamm !

Thanks for the report!
Fixed with 5cc4da2a28fa9b8ea7c915796658ed12faf516e4
