### ISSUE TITLE
TOR install fails on local

### ISSUE THREAD

**Issue by syloktools** [ail-project/ail-framework#63]
Ubuntu 20.04 clean install

Running the crawler install is failing at the line below:
./crawler_hidden_services_install.sh: line 46: install_python_requirement: command not found

```
Setting up dnsmasq-base (2.80-1.1ubuntu1) ...
Setting up ubuntu-fan (0.12.13) ...
Created symlink /etc/systemd/system/multi-user.target.wants/ubuntu-fan.service → /lib/systemd/system/ubuntu-fan.service.
Processing triggers for systemd (245.4-4ubuntu3.3) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for dbus (1.12.16-2ubuntu2.1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.1) ...
Using default tag: latest
latest: Pulling from scrapinghub/splash
7595c8c21622: Pull complete
d13af8ca898f: Pull complete
70799171ddba: Pull complete
b6c12202c5ef: Pull complete
60a588d4f36e: Pull complete
74efcc44bb0a: Pull complete
630a03095961: Pull complete
6ece3b427ef5: Pull complete
a1fce8353093: Pull complete
3933ca5f4768: Pull complete
b0097a197686: Pull complete
eb38ff0231d8: Pull complete
3d065f0b97ea: Pull complete
bce087e2552e: Pull complete
86c96f1d4ecd: Pull complete
3c421ffe4e4a: Pull complete
3c667b2546ea: Pull complete
765d9dad919d: Pull complete
f20aa104f0ea: Pull complete
bc2ee8c11554: Pull complete
185117d6d955: Pull complete
a40af7862b2f: Pull complete
38a6d08ed185: Pull complete
a36db9d4a71b: Pull complete
adaa646ebfe9: Pull complete
6ae21b55ecfd: Pull complete
8ef8d76a1942: Pull complete
Digest: sha256:b4173a88a9d11c424a4df4c8a41ce67ff6a6a3205bd093808966c12e0b06dacf
Status: Downloaded newer image for scrapinghub/splash:latest
docker.io/scrapinghub/splash:latest
./crawler_hidden_services_install.sh: line 46: install_python_requirement: command not found
```

**Comment by certrik** [comment]
True . There is an error in the script `./crawler_hidden_services_install.sh` if you run it with parameters. As a workaround just execute the script without parameters and answer `Y`.  Or just comment out line 46 in the script (be careful this might break update functionality via automatic `git clone`).
If you have a look into the script you can see that the function `install_python_requirement` has been commented out and I can confirm from a succesful installation that it is not needed anymore.
But you are right the install with parameters is still present in the documentation.

**Comment by lucadigregorio** [comment]
Guys, i have installed the crawler through the `./crawler_hidden_services_install.sh`. Everything goes as expected. Are you sure did you follow the procedure as explained in the `HOWTO.md` guide ? 
Are you installing local or remote ?
