### ISSUE TITLE
pystemon_feeder.py not working

### ISSUE THREAD

**Issue by lucadigregorio** [ail-project/ail-framework#76]
Hi Guys,
Few days ago i decided to switch to the latest version of AIL framework (v3.4). 
I've installed it according your guide lines. I have installed also pystemon and i use the same configuration used in the v3.3.
The problem is that pystemon does not work and i'm going to be crazy. I try to do all the suggested steps related to other issue about pystemon and pystemon_feeder. And i really can't understand what's wrong. Under the hoods it seems that all works fine, but i can't see any results on the AIL framework.
Some suggestions about this issue? I'm using AIL v3.4

Below i will put some screenshot which could be helpful to understand how things it's going under the hoods:
This is the AIL core.cfg to show the pystemon path modified
![AIL-core cfg-file](https://user-images.githubusercontent.com/49645452/106731633-fa9bf700-660f-11eb-87ef-8c071e05afe6.png)
This is the pystemon.yaml file modified according to your guide line
![pystemon-yaml-configuration-file](https://user-images.githubusercontent.com/49645452/106731692-0edff400-6610-11eb-8416-32f3bfd14b96.png)
This is the OUTPUT screenshot of the `pystemon_feeder.py`script
![OUTPUT-pystemon_feeder](https://user-images.githubusercontent.com/49645452/106734639-8b280680-6613-11eb-80d4-a9132d06100c.png)
This is the OUTPUT screenshot of the `pystemon.py`script 
![OUTPUT-pystemon](https://user-images.githubusercontent.com/49645452/106731970-6d0cd700-6610-11eb-92d5-8c26cd07d520.png)
This is the OUTPUT of the redis 
![OUTPUT-redis_check](https://user-images.githubusercontent.com/49645452/106732034-7e55e380-6610-11eb-9814-ed746836e53f.png)
This is what i can see from the AIL-framework
![AIL-framework-home-page](https://user-images.githubusercontent.com/49645452/106732126-9af21b80-6610-11eb-9aee-49cc3b05ffd3.png)

Thanks in advance!

**Comment by adulau** [comment]
As discussed via email, maybe doc can be updated as the issue is solved on your side. Thanks a lot for the tests.
