### ISSUE TITLE
possible bug in configuration parsers for IP script

### ISSUE THREAD

**Issue by certrik** [ail-project/ail-framework#85]
In my `configs/core.cfg` I have defined some IP ranges 
```
[IP]
networks = 172.34.34.0/24,192.168.1.0/24
```
in CIDR notification (for testing just some bogus ranges) but I can see in `screen -r Script_AIL` that there seems to be some problem ...
`Please provide a list of valid IP addresses`

**Comment by Terrtia** [comment]
Hi @certrik !

I didn't manage to reproduce it. I added  some debug output and a new message if the network is empty.
Can you please check if you still have this error message ?

**Comment by certrik** [comment]
Hi @Terrtia , I don't know why because I looked at your changes but it seems to work now. So thank you.
