### ISSUE TITLE
Crawler shows all domains `DOWN`

### ISSUE THREAD

**Issue by Gr3gbug** [ail-project/ail-framework#87]
Dears, 
I've installed the AIL-Crawler a few weeks ago (local installation), following your guidelines at `HOWTO.md`. Few days ago, suddenly, the crawler starts to show all domains to be `DOWN`, both regular crawler and onion crawler (and it's not). For what concern the onion crawler I try to understand what's wrong with that but i can't figure out. I double check the tor configuration, and the tor service works properly. 
Could you help me ? 
Here you can find the screen of `Crawler_AIL`
--> NameError: name 'request' is not defined
![Crawler_AIL](https://user-images.githubusercontent.com/49645452/109124158-e6e53b80-774a-11eb-8990-f27cb90c341d.png)

-->Here instead i post the screen of `Script_AIL` which currently shows that onion domain are properly sent to the crawler module
![onion_crawler](https://user-images.githubusercontent.com/49645452/109124386-26ac2300-774b-11eb-9ed5-104bddae8ab0.png)

If you need other information for debugging, ask me

**Comment by pressi96** [comment]
Same issue, how do you solve it?
