### ISSUE TITLE
Crawling error

### ISSUE THREAD

**Issue by rmsferreira** [ail-project/ail-framework#9]
HI,

when I start crawling onion sites, all appears down on dashboard.

After view the screen running the Crawler_AIL I have this error:

Traceback (most recent call last):
  File "./Crawler.py", line 413, in <module>
    crawler_config = load_crawler_config(to_crawl['type_service'], url_data['domain'], to_crawl['paste'],  to_crawl['url'], date)
  File "./Crawler.py", line 189, in load_crawler_config
    crawler_config['crawler_options'] = get_crawler_config(redis_crawler, 'auto', service_type, domain, url=url)
  File "./Crawler.py", line 173, in get_crawler_config
    crawler_options['time'] = int(config['time'])
KeyError: 'time'

**Comment by Terrtia** [comment]
Hi @rmsferreira !
Thanks for the report, fixed with 999157049988df9d14ec40dfd8a41db18cae1551.

You just need to delete and recreate all the domains that you want to monitor (auto crawler).
