### ISSUE TITLE
File Submission does not work anymore

### ISSUE THREAD

**Issue by Gr3gbug** [ail-project/ail-framework#98]
Hi guys, 
I don't if this issue is related to the latest update or not. Anyway, if i try to manually upload a file through the submit module, here is what happens: AIL remains stuck in this way:
![Screenshot 2021-04-09 083717](https://user-images.githubusercontent.com/49645452/114139175-fee5d880-990e-11eb-97cf-44b177fcb6b7.png)

**Comment by Terrtia** [comment]
Hi @Gr3gbug !

Can you check the output of  the ``submit_paste`` module ?

1) Access the script screen: 
``screen -r Script_AIL``

2) Select the SubmitPaste window:
``C-a "``

**Comment by bl00droot** [comment]
Hi @Terrtia SubmitPaste does not exist.

 
![image](https://user-images.githubusercontent.com/14825106/114441782-30c29d80-9ba2-11eb-9315-e57147ea8a51.png)

**Comment by bl00droot** [comment]
one information about the submit for is in:

`screen -r Flask`
and loading for hous/days?
![image](https://user-images.githubusercontent.com/14825106/114443134-b561eb80-9ba3-11eb-846c-6212347c0be2.png)

**Comment by Gr3gbug** [comment]
Hi @Terrtia, the output from submitePaste module is still the same. I try this morning to upload something manual, here is the output:
![image](https://user-images.githubusercontent.com/49645452/116805717-8a2a4680-ab28-11eb-9ce1-266b38202386.png)

**Comment by osagit** [comment]
@Gr3gbug Can you try with my Pull Request ? and give me feedback
https://github.com/ail-project/ail-framework/pull/103

**Comment by awakenine** [comment]
Hi Everyone,

I've got one more similar error with "sflock not found".
I have run the following command on the AIL instance to install required dependency:

```
source AILENV/bin/activate
sudo apt install libjpeg8-dev zlib1g-dev
pip3 install sflock
```
then it launched normally with working File Submission.

**Comment by awakenine** [comment]
Hi Everyone,

I've got one more similar error with "sflock not found".
I have run the following command on the AIL instance to install required dependency:

```
source AILENV/bin/activate
sudo apt install libjpeg8-dev zlib1g-dev
pip3 install sflock
```
then I launched it with `./LAUNCH.sh -l` and File Submission works.

**Comment by Terrtia** [comment]
Fixed, sflock (unmaintained) has been removed from the list of AIL requirements.
