### ISSUE TITLE
Exclude changes in .../splash/proxy-profiles/default.ini from update check

### ISSUE THREAD

**Issue by certrik** [ail-project/ail-framework#99]
Hi @Terrtia ,
Would it be a problem to also exclude changes in `ail-framework/configs/docker/splash_onion/etc/splash/proxy-profiles/default.ini` from the update check?
I guess not everybody is using the docker standard IPs. At least I don't because OPS is forcing a different CIDR on me.

**Comment by Terrtia** [comment]
Fixed in AIL v5.0
AIL crawler has been upgraded to [Lacus](https://github.com/ail-project/lacus)
the AIL crawler no longer relies on any Docker image.
